use_frameworks!

target 'CardStackView_Example' do
  pod 'CardStackView', :path => '../'

  target 'CardStackView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.2'
    pod 'Nimble', '~> 7.3.1'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end
